export const FEATURED_ACTION_TYPES = {
    FETCH_FEATURED_START: 'featured/FETCH_FEATURED_START',
    FETCH_FEATURED_SUCCESS: 'featured/FETCH_FEATURED_SUCCESS',
    FETCH_FEATURED_FAILED: 'featured/FETCH_FEATURED_FAILED',
};

